server:
  port: 8081

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/account_db
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "microservice-logging.yml"

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
